apiVersion: apps/v1
kind: Deployment
metadata:
  name: valorant-service
  namespace: valorant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valorant-service
  template:
    metadata:
      labels:
        app: valorant-service
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: tier
                    operator: In
                    values: ["core"]
      containers:
        - name: valorant-service
          image: ghcr.io/drome05/valorant-service:27ee8a1c2b23aae38c2229dd0db88777203ea412
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: valorant-secrets
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
