apiVersion: apps/v1
kind: Deployment
metadata:
  name: economy-service
  namespace: economy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: economy-service
  template:
    metadata:
      labels:
        app: economy-service
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: tier
                    operator: In
                    values: ["core"]
      containers:
        - name: economy-service
          image: economy-service:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
