apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: casino
---
apiVersion: v1
kind: Namespace
metadata:
  name: economy
---
apiVersion: v1
kind: Namespace
metadata:
  name: valorant
---
apiVersion: v1
kind: Namespace
metadata:
  name: inhouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: twitch
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: chat
